### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by edsum** [CaiWanFeng/PiP#11]
我想在老工程，就是AppDelegate为应用入口，没有SceneDelegate类的工程中，使用画中画功能，但是始终报错：The UIScene for the content source has an activation state other than UISceneActivationStateForegroundActive, which is not allowed。

如果我现在改成成SceneDelegate的工程，成本太大，很多地方调用[UIApplication sharedApplication].keyWindow方法无法使用，一些三方库我还没法去改。

**Comment by CaiWanFeng** [comment]
把 SceneDelegate 中的业务代码写到 AppDelegate 对应的方法中即可。
